export const mobileApps = [
  {
    nb: "03",
    name: "Sidegame",
    position: "Full Stack Web & Mobile Developer • UI & UX Designer",
    tech: [
      { name: "React Native", url: "https://reactnative.dev" },
      { name: "React js", url: "https://reactjs.org" },
      { name: "Nextjs", url: "https://nextjs.org" },
      { name: "Redux", url: "https://redux.js.org" },
      { name: "Firebase", url: "https://firebase.google.com" },
      {
        name: "Push Notification",
        url: "https://firebase.google.com/docs/cloud-messaging",
      },
      { name: "Google Cloud Platform", url: "https://cloud.google.com" },
      { name: "Google Admob", url: "https://admob.google.com" },
      { name: "Google Play Console", url: "https://play.google.com/console" },
      { name: "Android", url: "https://developer.android.com" },
      { name: "IOS", url: "https://developer.apple.com" },
    ],
    desc: "Developed a mobile application for football fans, featuring live scores, news, match details, quizzes, in-app store, push notification, and game features. Continuously updated to ensure optimal user experience.",
    platform: "ios & android app • web dashboard",
    imagesFolder: "sidegame",
    ios: {
      isShown: true,
      text: "ios ",
      link: null,
    },
    android: {
      isShown: true,
      text: "android app ",
      link: "https://play.google.com/store/apps/details?id=com.superstudiouniverse.sidegame",
    },
    web: {
      isShown: true,
      text: "web dashboard",
      link: null,
    },
    isMobile: true,
    neonColors: { firstColor: "#75b838", secondColor: "#4cdde4" },
    company: "🏡 Home"
  },
  {
    nb: "04",
    name: "Medipocket World",
    position: "Full Stack Web & Mobile Developer • UI & UX Designer",
    tech: [
      { name: "React Native", url: "https://reactnative.dev" },
      { name: "React js", url: "https://reactjs.org" },
      { name: "Redux", url: "https://redux.js.org" },
      { name: "Node js", url: "https://nodejs.org" },
      { name: "Firebase", url: "https://firebase.google.com" },
      { name: "Graphql", url: "https://graphql.org" },
      {
        name: "Apollo Client",
        url: "https://www.apollographql.com/docs/react/",
      },
      { name: "REST API", url: "https://restfulapi.net" },
      { name: "Stripe", url: "https://stripe.com" },
      { name: "Apple App Store", url: "https://developer.apple.com/app-store" },
      { name: "Google Play Console", url: "https://play.google.com/console" },
      { name: "Android", url: "https://developer.android.com" },
      { name: "IOS", url: "https://developer.apple.com" },
    ],
    desc: "Developed MediPocket, a healthcare app that connects patients worldwide with top-rated US specialists and hospitals. Enjoy personalized care, expert opinions, an AI symptom checker, video call, and Stripe payment options.",
    platform: "ios ,android and Progressive Web App",
    imagesFolder: "medipocket",
    ios: {
      isShown: true,
      text: "ios",
      link: null,
    },
    android: {
      isShown: true,
      text: "android app",
      link: "https://play.google.com/store/apps/details?id=com.medipocket.world",
    },
    web: {
      isShown: true,
      text: "Progressive Web App",
      link: "https://main.d2zgh6ymprehn7.amplifyapp.com",
    },
    isMobile: true,
    neonColors: { firstColor: "#01d7bb", secondColor: "#8df6e8" },
    company: "Allied Technologies"
  },
  {
    nb: "05",
    name: "RideShare",
    position: "Frontend Mobile Developer",
    tech: [
      { name: "React Native", url: "https://reactnative.dev" },
      { name: "Redux", url: "https://redux.js.org" },
      { name: "Google Maps API", url: "https://developers.google.com/maps" },
    ],
    desc: "Developed RideShare, a mobile app with a user-friendly UI/UX design, featuring a bottom sheet and Google Maps API integration for easy navigation and ride requests.",
    platform: "ios & android app",
    imagesFolder: "rideshare",
    ios: {
      isShown: true,
      text: "ios",
      link: null,
    },
    android: {
      isShown: true,
      text: "android app",
      link: null,
    },
    web: {
      isShown: false,
      text: "Progressive Web App",
      link: null,
    },
    isMobile: true,
    neonColors: { firstColor: "#ffffff", secondColor: "#0091ff" },
    company: "🏡 Home"
  },
  {
    nb: "06",
    name: "Hearppl",
    position: "Full Stack Web & Mobile Developer",
    tech: [
      { name: "React Native", url: "https://reactnative.dev" },
      { name: "Redux", url: "https://redux.js.org" },
      { name: "Firebase", url: "https://firebase.google.com" },
    ],
    desc: "Created and designed a mobile app that features short videos, allowing users to upload their own content and engage with others. With the ability to like, comment, and follow other users, the app creates a personalized video feed for each user based on hashtags.",
    platform: "ios & android app",
    imagesFolder: "hearppl",
    ios: {
      isShown: true,
      text: "ios",
      link: null,
    },
    android: {
      isShown: true,
      text: "android app",
      link: null,
    },
    web: {
      isShown: false,
      text: "Web App",
      link: null,
    },
    isMobile: true,
    neonColors: { firstColor: "#ffffff", secondColor: "#ff6d89" },
    company: "Allied Technologies"
  },
  {
    nb: "07",
    name: "Ertnashville",
    position: "Full Stack Mobile Developer",
    tech: [
      { name: "React Native", url: "https://reactnative.dev" },
      { name: "Redux", url: "https://redux.js.org" },
      { name: "Firebase", url: "https://firebase.google.com" },
    ],
    desc: "Designed and developed a mobile app that lets users make phone calls, create property listings and share access, upload photos, set security rules, and provide guidance to other users. It's a one-stop-shop for managing properties, and it's intuitive and user-friendly.",
    platform: "ios & android app",
    imagesFolder: "ertnashville",
    ios: {
      isShown: true,
      text: "ios",
      link: null,
    },
    android: {
      isShown: true,
      text: "android app",
      link: null,
    },
    web: {
      isShown: false,
      text: "Web App",
      link: null,
    },
    isMobile: true,
    neonColors: { firstColor: "#f70103", secondColor: "#7273f4" },
    company: "Allied Technologies"
  },
  {
    nb: "08",
    name: "D2",
    position: "Full Stack Web & Mobile Developer",
    tech: [
      { name: "React Native", url: "https://reactnative.dev" },
      { name: "Redux", url: "https://redux.js.org" },
      { name: "Firebase", url: "https://firebase.google.com" },
      { name: "Google Maps API", url: "https://developers.google.com/maps" },
    ],
    desc: "Created a mobile app for ride-hailing and home delivery. Passengers can easily request a ride or delivery while drivers can check and confirm rides before completing them through the same app.",
    platform: "ios & android app",
    imagesFolder: "d2",
    ios: {
      isShown: true,
      text: "ios",
      link: null,
    },
    android: {
      isShown: true,
      text: "android app",
      link: null,
    },
    web: {
      isShown: false,
      text: "Web App",
      link: null,
    },
    isMobile: true,
    neonColors: { firstColor: "#ff7008", secondColor: "#ffffff" },
    company: "🏡 Home"
  },
];

export const webApps = [
  {
    nb: "01",
    name: "ESG-Suite",
    position: "Frontend Engineer",
    tech: [
      { name: "Next js", url: "https://nextjs.org" },
      { name: "TypeScript", url: "https://www.typescriptlang.org" },
      { name: "Redux", url: "https://redux.js.org" },
      { name: "Tailwind CSS", url: "https://tailwindcss.com" },
      { name: "REST API", url: "https://restfulapi.net" },
      { name: "Mapbox", url: "https://www.mapbox.com" },
      { name: "HERE Maps", url: "https://developer.here.com" },
      {
        name: "Azure DevOps",
        url: "https://azure.microsoft.com/en-us/services/devops/",
      },
      { name: "Content Layer", url: "https://www.contentlayer.dev" },
      { name: "Resend - React Email", url: "https://resend.com" },
      { name: "Clerk", url: "https://clerk.dev" },
      { name: "Shadcn/ui", url: "https://ui.shadcn.com" },
      { name: "Sentry", url: "https://sentry.io" },
      { name: "Framer Motion", url: "https://www.framer.com/api/motion/" },
      { name: "Docker", url: "https://www.docker.com" },
      { name: "Zod", url: "https://zod.dev" },
      { name: "Jest", url: "https://jestjs.io" },
      { name: "Playwright", url: "https://playwright.dev" },
    ],
    desc: "Developed the ESG-Suite, featuring Solar-Analytics and Energy-Check. Improved building management, modernization, and investment decisions with API-driven data and detailed reporting.",
    platform: "web app",
    imagesFolder: "esg-suite",
    ios: {
      isShown: false,
      text: "",
      link: null,
    },
    android: {
      isShown: false,
      text: "",
      link: null,
    },
    web: {
      isShown: true,
      text: "web dashboard",
      link: "https://credium-esg-dev.azurewebsites.net",
    },
    isMobile: false,
    neonColors: { firstColor: "#325dec", secondColor: "#b0bff0" },
    company: "credium GmbH"
  },
  // {
  //   nb: "02",
  //   name: "Impulsive",
  //   position: "Software Engineer",
  //   tech: [
  //     { name: "Next js", url: "https://nextjs.org" },
  //     { name: "TypeScript", url: "https://www.typescriptlang.org" },
  //     { name: "Redux", url: "https://redux.js.org" },
  //     { name: "Tailwind CSS", url: "https://tailwindcss.com" },
  //     { name: "REST API", url: "https://restfulapi.net" },
  //     { name: "Stripe", url: "https://stripe.com" },
  //     { name: "Content Layer", url: "https://www.contentlayer.dev" },
  //     { name: "Resend - React Email", url: "https://resend.com" },
  //     { name: "Clerk", url: "https://clerk.dev" },
  //     { name: "Shadcn/ui", url: "https://ui.shadcn.com" },
  //     { name: "Vercel", url: "https://vercel.com" },
  //     { name: "Zod", url: "https://zod.dev" },
  //     { name: "Sentry", url: "https://sentry.io" },
  //     { name: "Vitest", url: "https://vitest.dev" },
  //   ],
  //   desc: "Developed a mobile application for football fans, featuring live scores, news, match details, quizzes, in-app store, push notification, and game features. Continuously updated to ensure optimal user experience.",
  //   platform: "ios & android app • web dashboard",
  //   imagesFolder: "sidegame",
  //   ios: {
  //     isShown: true,
  //     text: "ios ",
  //     link: null,
  //   },
  //   android: {
  //     isShown: false,
  //     text: "",
  //     link: "",
  //   },
  //   web: {
  //     isShown: true,
  //     text: "web dashboard",
  //     link: "https://impulsive.vercel.app",
  //   },
  //   isMobile: false,
  //   neonColors: { firstColor: "#7cbc40", secondColor: "#00FFF1" },
  //   company: "🏡 Home"
  // },
];
